# Generated by Django 2.2.5 on 2020-02-20 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadDocount', models.IntegerField(default=0, verbose_name='Visit Count')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('Datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('path', models.CharField(max_length=32, verbose_name='Download path')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Filename')),
                ('Filesize', models.CharField(max_length=10, verbose_name='Filesize')),
                ('PCIP', models.CharField(default='', max_length=32, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'download',
                'db_table': 'download',
            },
        ),
    ]
